import Head from "next/head";
import Nav from "@/components/Nav";
import Link from "next/link";

export default function PrivacyPage() {
  return (
    <div>
      <Head>
        <title>{`Privacy Policy | Gin+Tonic`}</title>
        <meta
          name="description"
          content={
            "G&T Creative Agency Sdn. Bhd. (“us”, “we”, or “our”) operates the www.ginplustonic.co website (the “Service”). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data."
          }
          key="desc"
        />
        <meta property="og:title" content={`Contact | Gin+Tonic`} />
        <meta
          property="og:description"
          content={
            "G&T Creative Agency Sdn. Bhd. (“us”, “we”, or “our”) operates the www.ginplustonic.co website (the “Service”). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data."
          }
        />
        {/* <meta property="og:image" content={coverImage?.fields.file.url || ""} /> */}
      </Head>
      <Nav bg="black" />
      <main className="max-h-max">
        <section>
          <div className="min-w-full h-[140px] bg-white"></div>
        </section>
      </main>
      <section className="bg-white text-black left-0 top-0 w-full origin-top overflow-hidden px-6 sm:px-8">
        <div className="max-w-screen-xl mx-auto pt-8 sm:pt-16 md:pt-24">
          <h1 className="text-[36px] sm:text-[42px] md:text-[48px] font-medium pb-8 md:pb-32 w-full md:w-[60%]">
            Privacy Policy
          </h1>
          <div className="grid grid-cols-1 md:grid-cols-2">
            <div className="flex flex-col font-medium text-[18px] text-gray-400 pb-16">
              <h2 className="justify-start">Effective Date</h2>
              <p className="text-gray-700">26 June 2024</p>
              <span className="pb-[12px]"></span>
            </div>
            <div className="">
              {/* <h1 className="font-medium text-[26px] md:text-[28px] pb-8">
                <p>Privacy Header</p>
              </h1> */}
              <div className="pb-[88px]">
                <p>
                  G&amp;T Creative Agency Sdn. Bhd. (“us”, “we”, or “our”)
                  operates the www.ginplustonic.co website (the “Service”).
                </p>
                <br />
                <p>
                  This page informs you of our policies regarding the
                  collection, use, and disclosure of personal data when you use
                  our Service and the choices you have associated with that
                  data.
                </p>
                <br />

                <p>
                  We use your data to provide and improve the Service. By using
                  the Service, you agree to the collection and use of
                  information in accordance with this policy. Unless otherwise
                  defined in this Privacy Policy, terms used in this Privacy
                  Policy have the same meanings as in our Terms and Conditions,
                  accessible from www.ginplustonic.co
                </p>
                <br />

                <h2 id="definitions" className="text-[22px] font-bold py-4">
                  Definitions
                </h2>
                <br />

                <p>
                  <strong>Service</strong>
                  <br />
                  Service is the www.ginplustonic.co website operated by G&amp;T
                  Creative Agency Sdn. Bhd.
                </p>
                <br />

                <p>
                  <strong>Personal Data</strong> <br />
                  Personal Data means data about a living individual who can be
                  identified from those data (or from those and other
                  information either in our possession or likely to come into
                  our possession).
                </p>
                <br />

                <p>
                  <strong>Usage Data</strong> <br />
                  Usage Data is data collected automatically either generated by
                  the use of the Service or from the Service infrastructure
                  itself (for example, the duration of a page visit).
                </p>
                <br />

                <p>
                  <strong>Cookies</strong> <br />
                  Cookies are small pieces of data stored on your device
                  (computer or mobile device).
                </p>
                <br />

                <p>
                  <strong>Data Controller</strong> <br />
                  Data Controller means the natural or legal person who (either
                  alone or jointly or in common with other persons) determines
                  the purposes for which and the manner in which any personal
                  information are, or are to be, processed.
                </p>
                <br />

                <p>
                  For the purpose of this Privacy Policy, we are a Data
                  Controller of your Personal Data.
                </p>
                <br />

                <p>
                  Data Processors (or Service Providers) Data Processor (or
                  Service Provider) means any natural or legal person who
                  processes the data on behalf of the Data Controller.
                </p>
                <br />

                <p>
                  We may use the services of various Service Providers in order
                  to process your data more effectively.
                </p>
                <br />

                <p>
                  <strong>Data Subject (or User)</strong> <br />
                  Data Subject is any living individual who is using our Service
                  and is the subject of Personal Data.
                </p>
                <br />

                <h2
                  id="information-collection-and-use"
                  className="text-[22px] font-bold py-4"
                >
                  Information Collection and Use
                </h2>
                <br />

                <p>
                  We collect several different types of information for various
                  purposes to provide and improve our Service to you.
                </p>
                <br />

                <p>Types of Data Collected</p>
                <br />

                <p>
                  <strong>PERSONAL DATA</strong> <br />
                  While using our Service, we may ask you to provide us with
                  certain personally identifiable information that can be used
                  to contact or identify you (“Personal Data”). Personally
                  identifiable information may include, but is not limited to:
                </p>
                <br />

                <ul>
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                  <li>Cookies and Usage Data</li>
                </ul>
                <br />

                <p>
                  We may use your Personal Data to contact you with newsletters,
                  marketing or promotional materials and other information that
                  may be of interest to you. You may opt out of receiving any,
                  or all, of these communications from us by following the
                  unsubscribe link or instructions provided in any email we send
                  or by contacting us.
                </p>
                <br />

                <p>
                  <strong>USAGE DATA</strong> <br />
                  We may also collect information how the Service is accessed
                  and used (“Usage Data”). This Usage Data may include
                  information such as your computer’s Internet Protocol address
                  (e.g. IP address), browser type, browser version, the pages of
                  our Service that you visit, the time and date of your visit,
                  the time spent on those pages, unique device identifiers and
                  other diagnostic data.
                </p>
                <br />

                <p>
                  <strong>TRACKING &amp; COOKIES DATA</strong> <br />
                  We use cookies and similar tracking technologies to track the
                  activity on our Service and hold certain information.
                </p>
                <br />

                <p>
                  Cookies are files with small amount of data which may include
                  an anonymous unique identifier. Cookies are sent to your
                  browser from a website and stored on your device. Tracking
                  technologies also used are beacons, tags, and scripts to
                  collect and track information and to improve and analyse our
                  Service.
                </p>
                <br />

                <p>
                  You can instruct your browser to refuse all cookies or to
                  indicate when a cookie is being sent. However, if you do not
                  accept cookies, you may not be able to use some portions of
                  our Service.
                </p>
                <br />

                <p>
                  <strong>Examples of Cookies we use:</strong> <br />
                  Session Cookies. We use Session Cookies to operate our
                  Service. Preference Cookies. We use Preference Cookies to
                  remember your preferences and various settings. Security
                  Cookies. We use Security Cookies for security purposes.
                </p>
                <br />

                <p>
                  <strong>Use of Data</strong> <br />
                  G&amp;T Creative Agency Sdn. Bhd. uses the collected data for
                  various purposes:
                </p>
                <br />

                <ul className="list-disc list-inside">
                  <li>To provide and maintain our Service</li>
                  <li>To notify you about changes to our Service</li>
                  <li>
                    To allow you to participate in interactive features of our
                    Service when you choose to do so
                  </li>
                  <li>To provide customer support</li>
                  <li>
                    To gather analysis or valuable information so that we can
                    improve our Service
                  </li>
                  <li>To monitor the usage of our Service</li>
                  <li>To detect, prevent and address technical issues</li>
                  <li>
                    To provide you with news, special offers and general
                    information about other goods, services and events which we
                    offer that are similar to those that you have already
                    purchased or enquired about unless you have opted not to
                    receive such information
                  </li>
                  <li>
                    Legal Basis for Processing Personal Data Under General Data
                    Protection Regulation (GDPR)
                  </li>
                </ul>
                <br />

                <p>
                  If you are from the European Economic Area (EEA), G&amp;T
                  Creative Agency Sdn. Bhd. legal basis for collecting and using
                  the personal information described in this Privacy Policy
                  depends on the Personal Data we collect and the specific
                  context in which we collect it.
                </p>
                <br />

                <p>
                  G&amp;T Creative Agency Sdn. Bhd. may process your Personal
                  Data because: We need to perform a contract with you You have
                  given us permission to do so The processing is in our
                  legitimate interests and it’s not overridden by your rights To
                  comply with the law
                </p>
                <br />

                <p>
                  <strong>Retention of Data</strong> <br />
                  G&amp;T Creative Agency Sdn. Bhd. will retain your Personal
                  Data only for as long as is necessary for the purposes set out
                  in this Privacy Policy. We will retain and use your Personal
                  Data to the extent necessary to comply with our legal
                  obligations (for example, if we are required to retain your
                  data to comply with applicable laws), resolve disputes, and
                  enforce our legal agreements and policies. G&amp;T Creative
                  Agency Sdn. Bhd. will also retain Usage Data for internal
                  analysis purposes. Usage Data is generally retained for a
                  shorter period of time, except when this data is used to
                  strengthen the security or to improve the functionality of our
                  Service, or we are legally obligated to retain this data for
                  longer time periods.
                </p>
                <br />

                <p>
                  <strong>Transfer of Data</strong> <br />
                  Your information, including Personal Data, may be transferred
                  to — and maintained on — computers located outside of your
                  state, province, country or other governmental jurisdiction
                  where the data protection laws may differ than those from your
                  jurisdiction. Your consent to this Privacy Policy followed by
                  your submission of such information represents your agreement
                  to that transfer.
                </p>
                <br />

                <p>
                  G&amp;T Creative Agency Sdn. Bhd.. will take all steps
                  reasonably necessary to ensure that your data is treated
                  securely and in accordance with this Privacy Policy and no
                  transfer of your Personal Data will take place to an
                  organisation or a country unless there are adequate controls
                  in place including the security of your data and other
                  personal information.
                </p>
                <br />

                <h2
                  id="disclosure-of-data"
                  className="text-[22px] font-bold py-4"
                >
                  Disclosure of Data
                </h2>
                <br />

                <p>
                  <strong>Disclosure for Law Enforcement</strong> <br />
                  Under certain circumstances, G&amp;T Creative Agency Sdn. Bhd.
                  may be required to disclose your Personal Data if required to
                  do so by law or in response to valid requests by public
                  authorities (e.g. a court or a government agency).
                </p>
                <br />

                <p>
                  <strong>Legal Requirements</strong> <br />
                  G&amp;T Creative Agency Sdn. Bhd. may disclose your Personal
                  Data in the good faith belief that such action is necessary
                  to: To comply with a legal obligation To protect and defend
                  the rights or property of G&amp;T Creative Agency Sdn. Bhd. To
                  prevent or investigate possible wrongdoing in connection with
                  the Service To protect the personal safety of users of the
                  Service or the public To protect against legal liability
                </p>
                <br />

                <p>
                  <strong>Security of Data</strong> <br />
                  The security of your data is important to us, but remember
                  that no method of transmission over the Internet, or method of
                  electronic storage is 100% secure. While we strive to use
                  commercially acceptable means to protect your Personal Data,
                  we cannot guarantee its absolute security.
                </p>
                <br />

                <p>
                  Your Data Protection Rights Under General Data Protection
                  Regulation (GDPR) If you are a resident of the European
                  Economic Area (EEA), you have certain data protection rights.
                  G&amp;T Creative Agency Sdn. Bhd. aims to take reasonable
                  steps to allow you to correct, amend, delete, or limit the use
                  of your Personal Data.
                </p>
                <br />

                <p>
                  If you wish to be informed what Personal Data we hold about
                  you and if you want it to be removed from our systems, please
                  contact us.
                </p>
                <br />

                <p>
                  In certain circumstances, you have the following data
                  protection rights:
                </p>
                <br />

                <p>
                  The right to access, update or to delete the information we
                  have on you. Whenever made possible, you can access, update or
                  request deletion of your Personal Data directly within your
                  account settings section. If you are unable to perform these
                  actions yourself, please contact us to assist you. The right
                  of rectification. You have the right to have your information
                  rectified if that information is inaccurate or incomplete. The
                  right to object. You have the right to object to our
                  processing of your Personal Data. The right of restriction.
                  You have the right to request that we restrict the processing
                  of your personal information. The right to data portability.
                  You have the right to be provided with a copy of the
                  information we have on you in a structured, machine-readable
                  and commonly used format. The right to withdraw consent. You
                  also have the right to withdraw your consent at any time where
                  G&amp;T Creative Agency Sdn. Bhd. relied on your consent to
                  process your personal information. Please note that we may ask
                  you to verify your identity before responding to such
                  requests. You have the right to complain to a Data Protection
                  Authority about our collection and use of your Personal Data.
                  For more information, please contact your local data
                  protection authority in the European Economic Area (EEA).
                </p>
                <br />

                <p>
                  <strong>Service Providers</strong> <br />
                  We may employ third party companies and individuals to
                  facilitate our Service (“Service Providers”), to provide the
                  Service on our behalf, to perform Service-related services or
                  to assist us in analyzing how our Service is used. These third
                  parties have access to your Personal Data only to perform
                  these tasks on our behalf and are obligated not to disclose or
                  use it for any other purpose.
                </p>
                <br />

                <p>
                  <strong>Analytics</strong> <br />
                  We may use third-party Service Providers to monitor and
                  analyze the use of our Service.
                </p>
                <br />

                <p>
                  <strong>Google Analytics</strong> <br />
                  Google Analytics is a web analytics service offered by Google
                  that tracks and reports website traffic. Google uses the data
                  collected to track and monitor the use of our Service. This
                  data is shared with other Google services. Google may use the
                  collected data to contextualise and personalise the ads of its
                  own advertising network. You can opt-out of having made your
                  activity on the Service available to Google Analytics by
                  installing the Google Analytics opt-out browser add-on. The
                  add-on prevents the Google Analytics JavaScript (ga.js,
                  analytics.js, and dc.js) from sharing information with Google
                  Analytics about visits activity. For more information on the
                  privacy practices of Google, please visit the Google Privacy
                  &amp; Terms web page:
                  https://policies.google.com/privacy?hl=en
                </p>
                <br />

                <p>
                  <strong>Behavioral Remarketing</strong> <br />
                  G&amp;T Creative Agency Sdn. Bhd. uses remarketing services to
                  advertise on third party websites to you after you visited our
                  Service. We and our third-party vendors use cookies to inform,
                  optimize and serve ads based on your past visits to our
                  Service.
                </p>
                <br />

                <p>
                  <strong>Google AdWords</strong> <br />
                  Google AdWords remarketing service is provided by Google Inc.
                  You can opt-out of Google Analytics for Display Advertising
                  and customize the Google Display Network ads by visiting the
                  Google Ads Settings page: http://www.google.com/settings/ads
                  Google also recommends installing the Google Analytics Opt-out
                  Browser Add-on – https://tools.google.com/dlpage/gaoptout –
                  for your web browser. Google Analytics Opt-out Browser Add-on
                  provides visitors with the ability to prevent their data from
                  being collected and used by Google Analytics. For more
                  information on the privacy practices of Google, please visit
                  the Google Privacy &amp; Terms web page:
                  https://policies.google.com/privacy?hl=en
                </p>
                <br />

                <p>
                  <strong>Bing Ads Remarketing</strong> <br />
                  Bing Ads remarketing service is provided by Microsoft Inc. You
                  can opt-out of Bing Ads remarketing by visiting:
                  https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads
                  You can learn more about the privacy practices and policies of
                  Microsoft by visiting their Privacy Policy page:
                  https://privacy.microsoft.com/en-us/PrivacyStatement
                </p>
                <br />

                <p>
                  <strong>LinkedIn Ads &amp; Remarketing</strong> <br />
                  LinkedIn Ads remarketing service is provided by Microsoft Inc.
                  You can learn more about the privacy practices and policies of
                  Microsoft by visiting their Privacy Policy page:
                  https://privacy.microsoft.com/en-us/PrivacyStatement
                </p>
                <br />

                <p>
                  <strong>Twitter</strong> <br />
                  Twitter remarketing service is provided by Twitter Inc.
                  <br />
                  <br />
                  You can opt-out from Twitter’s interest-based ads by following
                  their instructions:
                  https://support.twitter.com/articles/20170405
                  <br />
                  <br />
                  You can learn more about the privacy practices and policies of
                  Twitter by visiting their Privacy Policy page:
                  https://twitter.com/privacy
                </p>
                <br />

                <p>
                  <strong>Facebook</strong> <br />
                  Facebook remarketing service is provided by Facebook Inc.
                  <br />
                  <br />
                  Youcan learn more about interest-based advertising from
                  Facebook by visiting this page:
                  https://www.facebook.com/help/164968693837950
                  <br />
                  <br />
                  To opt-out from Facebook’s interest-based ads follow these
                  instructions from Facebook:
                  https://www.facebook.com/help/568137493302217
                  <br />
                  <br />
                  Facebook adheres to the Self-Regulatory Principles for Online
                  Behavioral Advertising established by the Digital Advertising
                  Alliance. You can also opt-out from Facebook and other
                  participating companies through the Digital Advertising
                  Alliance in the USA http://www.aboutads.info/choices/, the
                  Digital Advertising Alliance of Canada in Canada
                  http://youradchoices.ca/ or the European Interactive Digital
                  Advertising Alliance in Europe
                  http://www.youronlinechoices.eu/, or opt-out using your mobile
                  device settings.
                  <br />
                  <br />
                  For more information on the privacy practices of Facebook,
                  please visit Facebook’s Data Policy:
                  https://www.facebook.com/privacy/explanation
                </p>
                <br />

                <p>
                  <strong>Links to Other Sites</strong> <br />
                  Our Service may contain links to other sites that are not
                  operated by us. If you click on a third party link, you will
                  be directed to that third party’s site. We strongly advise you
                  to review the Privacy Policy of every site you visit. We have
                  no control over and assume no responsibility for the content,
                  privacy policies or practices of any third party sites or
                  services.
                </p>
                <br />

                <p>
                  <strong>Children’s Privacy</strong> <br />
                  Our Service does not address anyone under the age of 18
                  (“Children”). We do not knowingly collect personally
                  identifiable information from anyone under the age of 18. If
                  you are a parent or guardian and you are aware that your child
                  has provided us with Personal Data, please contact us. If we
                  become aware that we have collected Personal Data from
                  children without verification of parental consent, we take
                  steps to remove that information from our servers.
                </p>
                <br />

                <p>
                  <strong>Changes to This Privacy Policy</strong> <br />
                  We may update our Privacy Policy from time to time. We will
                  notify you of any changes by posting the new Privacy Policy on
                  this page. We will let you know via email and/or a prominent
                  notice on our Service, prior to the change becoming effective
                  and update the “effective date” at the top of this Privacy
                  Policy. You are advised to review this Privacy Policy
                  periodically for any changes. Changes to this Privacy Policy
                  are effective when they are posted on this page.
                </p>
                <br />

                <p>
                  <strong>Contact Us</strong> <br />
                  If you have any questions about this Privacy Policy, please
                  contact us by visiting this page on our{" "}
                  <Link href={"/contact"} className="text-gray-500">
                    website.
                  </Link>
                </p>

                <br />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-white text-black left-0 top-0 w-full origin-top overflow-hidden"></section>
    </div>
  );
}
